chore(deps): Bump prettier from 3.1.0 to 3.2.2 (#213)
Bumps [prettier](https://github.com/prettier/prettier) from 3.1.0 to 3.2.2.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/prettier/prettier/releases">prettier's releases</a>.</em></p>
<blockquote>
<h2>3.2.2</h2>
<p>🔗 <a href="https://github.com/prettier/prettier/blob/main/CHANGELOG.md#322">Changelog</a></p>
<h2>3.2.1</h2>
<p>🔗 <a href="https://github.com/prettier/prettier/blob/main/CHANGELOG.md#321">Changelog</a></p>
<h2>3.2.0</h2>
<p><a href="https://github.com/prettier/prettier/compare/3.1.1...3.2.0">diff</a></p>
<p>🔗 <a href="https://prettier.io/blog/2024/01/12/3.2.0.html">Release note</a></p>
<h2>3.1.1</h2>
<p>🔗 <a href="https://github.com/prettier/prettier/blob/main/CHANGELOG.md#311">Changelog</a></p>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/prettier/prettier/blob/main/CHANGELOG.md">prettier's changelog</a>.</em></p>
<blockquote>
<h1>3.2.2</h1>
<p><a href="https://github.com/prettier/prettier/compare/3.2.1...3.2.2">diff</a></p>
<h4>Fix crash when parsing template literal CSS in a JSX style tag using a spread attribute (<a href="https://redirect.github.com/prettier/prettier/pull/15896">#15896</a> by <a href="https://github.com/eelco"><code>@​eelco</code></a>)</h4>
<p>For example this code would crash before:</p>
<!-- raw HTML omitted -->
<pre lang="jsx"><code>&lt;style {...spread}&gt;{`.{}`}&lt;/style&gt;
</code></pre>
<h4>Fix formatting error on optional call expression and member chain (<a href="https://redirect.github.com/prettier/prettier/pull/15920">#15920</a> by <a href="https://github.com/sosukesuzuki"><code>@​sosukesuzuki</code></a>)</h4>
<!-- raw HTML omitted -->
<pre lang="jsx"><code>// Input
a(() =&gt; {}, c?.d());
<p>// Prettier 3.2.1
TypeError: Cannot read properties of undefined (reading 'type')</p>
<p>// Prettier 3.2.2
a(() =&gt; {}, c?.d());
</code></pre></p>
<h1>3.2.1</h1>
<p><a href="https://github.com/prettier/prettier/compare/3.2.0...3.2.1">diff</a></p>
<h4>Fix formatting error on member chain (<a href="https://redirect.github.com/prettier/prettier/pull/15915">#15915</a> by <a href="https://github.com/sosukesuzuki"><code>@​sosukesuzuki</code></a>)</h4>
<!-- raw HTML omitted -->
<pre lang="jsx"><code>// Input
test().test2().test2(thing?.something);
<p>// Prettier 3.2.0
TypeError: Cannot read properties of undefined (reading 'type')</p>
<p>// Prettier 3.2.1
test().test2().test2(thing?.something);</p>
<p></code></pre></p>
<h1>3.2.0</h1>
<p><a href="https://github.com/prettier/prettier/compare/3.1.1...3.2.0">diff</a></p>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/prettier/prettier/commit/5f2c6df4629b1474be5002ff3c6f8ad4a666b70f"><code>5f2c6df</code></a> Release 3.2.2</li>
<li><a href="https://github.com/prettier/prettier/commit/cb8004f3f1141635e2a4993ab87d55fbe3b64fb7"><code>cb8004f</code></a> Fix formatting error on optional call expression and member chain (<a href="https://redirect.github.com/prettier/prettier/issues/15920">#15920</a>)</li>
<li><a href="https://github.com/prettier/prettier/commit/0bfcb2d5a544a09c94a7d6ca637f05271fa270ce"><code>0bfcb2d</code></a> Fix css embed in JSX when using (only) a spread attribute (<a href="https://redirect.github.com/prettier/prettier/issues/15896">#15896</a>)</li>
<li><a href="https://github.com/prettier/prettier/commit/12ab54898ca2a59826714c3027b8ce037cabdd6d"><code>12ab548</code></a> Add <code>prettier-plugin-gherkin</code> to the community plugins list (<a href="https://redirect.github.com/prettier/prettier/issues/15919">#15919</a>)</li>
<li><a href="https://github.com/prettier/prettier/commit/4ce96dd530613b99bb4a682ec93f719f3d4109f5"><code>4ce96dd</code></a> Fix typo (<a href="https://redirect.github.com/prettier/prettier/issues/15917">#15917</a>)</li>
<li><a href="https://github.com/prettier/prettier/commit/08f37968632dc2e72789160704c3f36268bf3c1c"><code>08f3796</code></a> Run <code>yarn</code></li>
<li><a href="https://github.com/prettier/prettier/commit/11aea0df1a9708c0c22f6a93b2662c1413f8d783"><code>11aea0d</code></a> Clean changelog_unreleased</li>
<li><a href="https://github.com/prettier/prettier/commit/75e66b8c444ec2a251f72917dbe5b58c4a210051"><code>75e66b8</code></a> Git blame ignore 3.2.1</li>
<li><a href="https://github.com/prettier/prettier/commit/5811ad00705488365e0d0baf50c92965edddf58e"><code>5811ad0</code></a> Bump Prettier dependency to 3.2.1</li>
<li><a href="https://github.com/prettier/prettier/commit/48ad20859bad01bf70ebc27051939c2329c52b18"><code>48ad208</code></a> Release 3.2.1</li>
<li>Additional commits viewable in <a href="https://github.com/prettier/prettier/compare/3.1.0...3.2.2">compare view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=prettier&package-manager=npm_and_yarn&previous-version=3.1.0&new-version=3.2.2)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)


</details>